### ISSUE TITLE
How to run???

### ISSUE THREAD

**Issue by pv33** [ivapylibs/Lie#2]
@varunm99 
Sorry to bug, but how does one run these things?
I am using python command line, which is the barest bones possible.  What I figure should work, based on my Matlab thinking, is:

> python

which goes into the command line.  I am in the ``~/python`` directory where all code gets cloned to.  Then I run the following:

```
import sys
sys.path.insert(0,'/home/pvela/python');
execfile('Lie/tests/testSE2.py')
```
and what is output is the following

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Lie/tests/testSE2.py", line 1, in <module>
    from Lie.group.SE3 import Homog
ImportError: No module named Lie.group.SE3
```

which tells me that you are doing something special somewhere to get things to work.  Maybe you are using an IDE or something and initially defined some environment variables that now automatically trigger whenever you run the IDE.  What is the command line equivalent to those variables or environment setting invocations?

How can I get this to run completely from the command line?
I am willing to have a few manually entered lines to get things setup before running the script.

**Comment by pv33** [comment]
@varunm99 
OK, one thing I did that made it better was to run
>> sys.path.insert(0,'/home/pvela/python/Lie');

and then things worked out.  The above line would be equivalent to the Matlab call

>> ivalab.loadLibraries( {'Lie'} );

Why do you not need that in your code? What are you doing to skirt around this issue? It is also probably affecting how you code things and how the namespaces work. Possibly, not sure yet.

Something is going on in your IDE. I want to know what that is.

**Comment by varunm99** [comment]
Did you install the Lie library (or whatever other libraries you're having issues with)?

Once you clone the repository, run 
```pip3 install -e ./```
from the same directory as the setup.py file. This uses pip to install the library on your computer. The "-e" flag means the library is editable so you can edit the file and it edits will be updated as they are made. 

If this solves your problem I will write up instructions and put them in this repository's README.

**Comment by pv33** [comment]
Confirming that using:

> pip3 install -e PACKAGE_DIR

works. Next is to simply flesh out the ``requirements.txt`` file as needed.  It would be nice to know is some basic management can be done like with ROS. Justin, another student, likes to build meta-packages that download things automatically when needed and not available.

Not sure if it is a ROS thing only.
